### ISSUE TITLE
生态维度新增-业界使用情况、增加创新的评估维度-组织多样性

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#433]
### Description

1. 分析组织活跃度如何展示：需要展示主流厂商使用情况
    - 按照 oss-insight 的页面的启发，展示相关数据
    - 左边展示项目，右边展示组织列表，并按照star排序
### Todo
- [ ] 创新的指标讨论下，加入到算分中
- [ ] 对比功能也要显示创新相关指标
- [ ] 导出功能也要有创新相关指标

**优化**
- [x] 现有接口的加载速度：业界使用情况的SQL查询慢，接口需要修改
- [x] 现有组织多样性 el-tabs 的切换更改为 v-model
- [ ] 气泡图的渲染逻辑，抽出为公共方法，并且修改显示 tips 和增加跳转链接（依赖软件跳转到GitHub的依赖图）
- [x] 增加tips来显示数据的出处
- [x] 组织多样性的异常数据过滤：需要增加 空、undefined、无等（持续做过滤名单列表）

**业界使用情况**：
- [ ] 知名组织的排名：按照 git-ranking 的 1000 org 来进行排名（tips为使用了该软件的知名组织，组织按照该组织在Github上的总star数进行排名）
- [ ] 知名项目：也是按照在Github上的总star数来排名，但项目不一定全，而是按照我们自己的表数据进行分析

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by flyfishzy** [comment]
TODO 待完善:
1. 创新的指标讨论下，加入到算分中
2. 对比功能也要显示创新相关指标
3. 导出功能也要有创新相关指标
